language: go
sudo: false

go:
  - 1.8.3

install:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
  - go get github.com/smartystreets/goconvey
  - cd $GOPATH/src/github.com/nedscode/memdb

script:
  - go vet
  - go get
  - overalls -project=github.com/nedscode/memdb -covermode=count -ignore='.git,_vendor'
  - goveralls -coverprofile=overalls.coverprofile -service=travis-ci
  - go test
